### ISSUE TITLE
Analisar os dados

### ISSUE THREAD

**Issue by Paulo3078** [FabricioMartinsss/avanti-bootcamp-cdd#2]
- [x] Criar perguntas de partida e hipóteses
- [x] Mostrar as estatísticas discretas dos dados
- [x] Criar gráficos para as variáveis quantitativas
- [x] Criar gráficos para as variáveis qualitativas
- [x] Expor os insights adquiridos

**Comment by fiuzatayna** [comment]
### Coleta inicial de dados e criação do dicionário de dados
 - [x] Adicionou o conjunto de dados na pasta `data/raw/`?
 - [x] Criou e salvou o dicionário de dados na pasta `data/external/`?

### Exploração de dados
Pontos positivos
 - [x] Escreveu uma descrição dos dados?
 - [ ] Falou sobre dados faltantes?
 - [x] Escreveu perguntas e partidas de hipóteses?
 - [ ] Utilizou mais que 3 tipos de gráficos?
 - [x] Escreveu um sumário dos *insights* no final?
 - [ ] Criou gráficos que não foram vistos em aula?
 - [x] Fez análise univariada?
 - [x] Fez análise bivariada?
 - [ ] Fez análise multivariada?

Pontos negativos
 - [ ] Usou canal de cor sem necessidade?
 - [ ] Utilizou rótulos inclinados?
 - [ ] Utilizou gráfico de dispersão quando deveria ter utilizado gráfico de boxplot?
 - [ ] Não ordenou gráficos de barra quando deveria?

---
### Comentários
De maneira geral, a análise está boa, com boas perguntas de hipótese e bons gráficos. Precisando melhorar somente nos seguintes pontos:
 - Utilizar cores diferentes somente quando for estritamente necessário

---
cc @omadson
